add project file structure
redacademy/bikelocker-spring-2019 pull request #34
Opened 2019-06-10 23:21 UTC by amarquesmoura

This pull request add initial file structure to our project.

2019-06-10 23:32 UTC, siddharthparmar7 requested changes
Please make the changes. Thank you.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/components/Search/index.js
> +import SearchContainer from "./SearchContainer";
Components do not have containers. Please make changes to your imports and exports.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/components/Search/index.js
> +export { Search };
Add missing Search.js file.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/components/MapView/index.js
> +import MapViewContainer from "./MapViewContainer";
Components do not have container files. Please remove MapViewContainer file. If it's a screen then move it to the screens dir.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/screens/About/index.js
> +import About from "./About";
About screen is missing a container file. Please add it.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/screens/Contact/index.js
> +import Contact from "./Contact";
Contact Screen is missing a container file. Please add it.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/screens/HowTo/index.js
> +import HowTo from "./HowTo";
Make this screen name more descriptive and add a container file.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/screens/Onboarding/index.js
> +import Onboarding from "./Onboarding";
Add a container file.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/screens/Resources/index.js
> +import Resources from "./Resources";
Add a container file. Thank you.

2019-06-10 23:32 UTC, siddharthparmar7 commented on js/screens/Spot/index.js
> +import Spot from "./Spot";
Add container file. Thank you.

2019-06-10 23:49 UTC, amarquesmoura commented
Adjustments made as requested.

2019-06-11 17:22 UTC, siddharthparmar7 commented
Please rebase your develop branch and then update your feature branch. To get the latest project structure on your machine.

2019-06-11 17:32 UTC, amarquesmoura commented
Done.

2019-06-11 17:33 UTC, siddharthparmar7 approved these changes

2019-06-11 17:34 UTC, merged